name: Docker Image CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only run for pushes or PRs from the main repo (not forks/dependabot)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag envidtech/mc-server-creator:latest

      - name: Push to Docker Hub
        run: docker push envidtech/mc-server-creator:latest

  # Separate job for external PRs (forks, dependabot) - build only (no push)
  build-only:
    runs-on: ubuntu-latest
    # Only run for pull requests from forks or dependabot
    if: github.event_name == 'pull_request' && (github.actor == 'dependabot[bot]' || github.event.pull_request.head.repo.full_name != github.repository)

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image (test only)
        run: docker build . --file Dockerfile --tag envidtech/mc-server-creator:test